[blackdoc]
    blacklist = [
        "venv",
        "virtualenv",
        "__pycache__",
        "build",
        "dist",
        "doc",
        "docs",
        "Docs",
        ".git",
        ".gitignore",
        ".idea",
        ".pytest_cache",
        "*.egg-info",
        "html"
    ]

    whitelist = []

    workers = 2
